name: ipycanvas-docs

channels:
  - conda-forge

dependencies:
  - ipycanvas
  - mamba
  # This is needed for building ipycanvas from source for the emscripten env
  - yarn
  # Docs requirements
  - pydata-sphinx-theme
  - jupyterlite-sphinx
  - jupyterlite-xeus-python >=0.9.2,<0.10
  - jupyterlab-night
