name: ipycanvas-docs

channels:
  - conda-forge

dependencies:
  - ipycanvas
  - micromamba=2.0.5
  - yarn
  # Docs requirements
  - pydata-sphinx-theme
  - jupyterlite-sphinx
  - jupyterlab-night
  - pip:
    - jupyterlite-xeus===0.4.0b0
