name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - ipycanvas
  - mamba
  - pydata-sphinx-theme
  - jupyterlite-sphinx
  - jupyterlite-xeus-python >=0.9.2<0.10
  - jupyterlab-night
