name: ipycanvas-docs

channels:
  - conda-forge

dependencies:
  - ipycanvas
  - micromamba
  - yarn
  # Docs requirements
  - pydata-sphinx-theme
  - jupyterlite-sphinx
  - jupyterlite-core
  - jupyterlite-xeus
  - jupyterlab-night
