name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - ipycanvas
  - mamba
  - pydata-sphinx-theme
  - empack

  - pip:
    - jupyterlite
    - jupyterlite-sphinx
    - jupyterlite-xeus-python
    - jupyterlab-night
